/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-inventory`; params?: Router.UnknownInputParams; } | { pathname: `/add-meal`; params?: Router.UnknownInputParams; } | { pathname: `/dispatch-takeout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/reconcile-takeout`; params?: Router.UnknownInputParams; } | { pathname: `/record-expense`; params?: Router.UnknownInputParams; } | { pathname: `/record-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/record-sale`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/add-meal`; params?: Router.UnknownOutputParams; } | { pathname: `/dispatch-takeout`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ledger`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/reconcile-takeout`; params?: Router.UnknownOutputParams; } | { pathname: `/record-expense`; params?: Router.UnknownOutputParams; } | { pathname: `/record-purchase`; params?: Router.UnknownOutputParams; } | { pathname: `/record-sale`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-inventory${`?${string}` | `#${string}` | ''}` | `/add-meal${`?${string}` | `#${string}` | ''}` | `/dispatch-takeout${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ledger${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/reconcile-takeout${`?${string}` | `#${string}` | ''}` | `/record-expense${`?${string}` | `#${string}` | ''}` | `/record-purchase${`?${string}` | `#${string}` | ''}` | `/record-sale${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-inventory`; params?: Router.UnknownInputParams; } | { pathname: `/add-meal`; params?: Router.UnknownInputParams; } | { pathname: `/dispatch-takeout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/reconcile-takeout`; params?: Router.UnknownInputParams; } | { pathname: `/record-expense`; params?: Router.UnknownInputParams; } | { pathname: `/record-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/record-sale`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
